import { createHash } from "crypto";
import { readFileSync } from "fs";
import fs from "fs/promises";
import { createRequire } from "module";
import os from "os";
import path from "path";
import { describe, expect, it } from "vitest";
import {
    generateAppRunScript,
    validateCriticalPathString as builderValidateCriticalPathString,
} from "app-builder-lib/out/targets/appimage/appImageUtil";
import { LinuxTargetHelper } from "app-builder-lib/out/targets/LinuxTargetHelper";
import {
    appImageCompression,
    appImageDesktopEntry,
    appImageEntries,
    appRunScript,
    validateCriticalPathString,
    writeAppImage,
    type AppImageOptions,
} from "./appImage";
import type { AppImageToolset } from "./appImageToolset";
import { squashfsZstdAvailable } from "./squashfs";
import { readSquashfs } from "./squashfsReader";

/**
 * Two things are tested here: that the AppImage is put together as electron-builder puts one
 * together, and that this stays true as electron-builder changes.
 *
 * The second is the reason most of this file exists. appImage.ts is a port of electron-builder's
 * AppImage target, and a port is only as good as the last time someone compared it with the
 * original. So the comparison is automatic, against the electron-builder that is installed: what
 * can be compared by output (the launcher, the desktop entry, the name check) is generated by both
 * and compared byte for byte, and what can only be compared by reading (where things go in the
 * image, the flags and compression electron-builder gives mksquashfs) is fingerprinted.
 */

const requireFromHere = createRequire(__filename);

function builderSource(file: string): string {
    return readFileSync(requireFromHere.resolve(`app-builder-lib/out/${file}`), "utf8");
}

/** The text of one top-level declaration in a compiled electron-builder file, up to its closing brace. */
function declarationIn(file: string, opening: string): string {
    const text = builderSource(file);
    const start = text.indexOf(opening);
    if (start === -1) {
        throw new Error(`${file} no longer declares "${opening}"`);
    }
    const end = text.indexOf("\n}\n", start);
    return text.slice(start, end + 2);
}

function fingerprint(source: string): string {
    return createHash("sha256").update(source.replace(/\s+/g, " ").trim()).digest("hex").slice(0, 16);
}

const builderVersion = (requireFromHere("app-builder-lib/package.json") as { version: string }).version;

describe("the AppImage pieces electron-builder generates, generated here", () => {
    const appRunCases: Array<Parameters<typeof appRunScript>[0]> = [
        { executableName: "skeleton-12", productName: "skeleton-12", productFilename: "skeleton-12" },
        { executableName: "my game", productName: "My Game", productFilename: "My Game" },
        { executableName: "游戏", productName: "It's \"quoted\" & $odd", productFilename: "游戏" },
        { executableName: "game", productName: "Game", productFilename: "Game", eula: { fileName: "license.txt", isHtml: false } },
        { executableName: "game", productName: "Rock 'n' Roll", productFilename: "Rock n Roll", eula: { fileName: "EULA.html", isHtml: true } },
    ];

    it.each(appRunCases)("writes the launcher electron-builder writes (%o)", options => {
        const builder = generateAppRunScript({
            ExecutableName: options.executableName,
            ProductName: options.productName,
            ProductFilename: options.productFilename,
            DesktopFileName: `${options.executableName}.desktop`,
            ResourceName: `appimagekit-${options.executableName}`,
            ...(options.eula ? { EulaFile: options.eula.fileName, IsHtmlEula: options.eula.isHtml } : {}),
        });
        expect(appRunScript(options)).toBe(builder);
    });

    const desktopCases: Array<Parameters<typeof appImageDesktopEntry>[0]> = [
        { productName: "skeleton-12", executableName: "skeleton-12", version: "1.0.0", description: "x" },
        { productName: "My Game", executableName: "my-game", version: "2.3.4-beta.1" },
        { productName: "Spaces", executableName: "spaces", version: "1.0.0", description: "   " },
        { productName: "Line\nBreak\\Tab\t", executableName: "lb", version: "1.0.0", description: "two\nlines" },
        { productName: "Named", executableName: "named", version: "1.0.0", desktopName: "com.example.named.desktop" },
        { productName: "Named", executableName: "named", version: "1.0.0", desktopName: "  plain-name  " },
        { productName: "Blank", executableName: "blank", version: "1.0.0", desktopName: "   " },
    ];

    it.each(desktopCases)("writes the desktop entry electron-builder writes (%o)", async options => {
        // The packager surface computeDesktopEntry reads, as a Studio build configures it: no
        // category, protocols, file associations, desktop overrides or launcher arguments.
        const packager = {
            appInfo: { productName: options.productName, description: options.description },
            executableName: options.executableName,
            info: { metadata: { desktopName: options.desktopName } },
            fileAssociations: [],
            config: {},
            platformSpecificBuildOptions: {},
        };
        const helper = new LinuxTargetHelper(packager as unknown as ConstructorParameters<typeof LinuxTargetHelper>[0]);
        // AppImageTarget's own call: the launcher and %U as Exec (the static toolset adds no
        // arguments), and the version as an extra field.
        const builder = await helper.computeDesktopEntry({}, "AppRun %U", { "X-AppImage-Version": options.version });
        expect(appImageDesktopEntry(options)).toBe(builder);
    });

    it.each([
        "skeleton-12",
        "My Game 2",
        "游戏.v1_x",
        "bad/slash",
        "bad\"quote",
        "bad$dollar",
        "",
        "tab\there",
    ])("accepts and refuses the names electron-builder does (%j)", name => {
        const builderAccepts = (() => {
            try {
                builderValidateCriticalPathString(name, "executableName");
                return true;
            } catch {
                return false;
            }
        })();
        if (builderAccepts) {
            expect(() => validateCriticalPathString(name, "executableName")).not.toThrow();
        } else {
            expect(() => validateCriticalPathString(name, "executableName")).toThrow(/executableName/);
        }
    });
});

/**
 * What appImage.ts ports by reading rather than by output, fingerprinted as installed.
 *
 * When one of these fails, electron-builder changed how it builds an AppImage. Read the new source
 * of the part named, bring appImage.ts (and appImageToolset.ts, for the toolset) in step with it,
 * and only then replace the fingerprint. Replacing it first is how a port silently becomes a fork.
 */
describe(`electron-builder's AppImage target (app-builder-lib ${builderVersion}), as appImage.ts ported it`, () => {
    const ported: Array<[string, string, string, string]> = [
        // Stage, copy libraries then app, mksquashfs flags, runtime in front, chmod, block map.
        ["targets/appimage/appImageUtil.js", "async function buildStaticRuntimeAppImage(", "c0d6e2d45f7cf8a4", "the staging order and mksquashfs flags"],
        // Desktop file name and mode, icons, MIME package, licence, AppRun mode.
        ["targets/appimage/appImageUtil.js", "async function writeAppLauncherAndRelatedFiles(", "54fe9f34437ba108", "the staged files"],
        // Icon directories, file names, and the two links to the largest.
        ["targets/appimage/appLauncher.js", "async function copyIcons(", "9ff1a9e67928074b", "the icon layout"],
        // Exec line per toolset, X-AppImage-Version, the compression picked per toolset and level.
        ["targets/appimage/AppImageTarget.js", "class AppImageTarget extends", "be890f0aaf62a719", "the desktop entry's inputs and the compression"],
        // Which archive, release and paths a toolset version means.
        ["toolsets/linux.js", "async function getAppImageTools(", "903b470fd28601f5", "the toolset layout"],
    ];

    it.each(ported)("%s: %s", (file, opening, expected, what) => {
        const actual = fingerprint(declarationIn(file, opening));
        expect(actual, `${what} changed in app-builder-lib ${builderVersion} (${file}); port the change, then update the fingerprint`).toBe(expected);
    });
});

const fakeToolset = (): AppImageToolset => ({
    // An ELF-looking stand-in; nothing here runs it.
    runtime: Buffer.concat([Buffer.from([0x7f, 0x45, 0x4c, 0x46]), Buffer.alloc(1000, 0xaa)]),
    libraries: [
        { kind: "file", path: "usr/lib/libXss.so.1.0.0", mode: 0o644, content: Buffer.from("xss") },
        { kind: "symlink", path: "usr/lib/libXss.so.1", target: "libXss.so.1.0.0" },
    ],
});

function options(overrides: Partial<AppImageOptions> = {}): AppImageOptions {
    return {
        app: [
            { kind: "file", path: "skeleton-12", mode: 0o755, content: Buffer.from([0x7f, 0x45, 0x4c, 0x46, 1, 2, 3]) },
            { kind: "file", path: "resources/app.asar", mode: 0o644, content: Buffer.from("asar") },
            { kind: "file", path: "LICENSE.electron.txt", mode: 0o644, content: Buffer.from("MIT") },
        ],
        toolset: fakeToolset(),
        executableName: "skeleton-12",
        productName: "skeleton-12",
        productFilename: "skeleton-12",
        version: "1.0.0",
        description: "x",
        icons: [
            { size: 256, png: Buffer.from("png256") },
            { size: 16, png: Buffer.from("png16") },
            { size: 64, png: Buffer.from("png64") },
        ],
        mtime: 1_700_000_000,
        ...overrides,
    };
}

describe("an AppImage's image", () => {
    it("holds what electron-builder's staging folder holds, with the app over it", () => {
        const entries = appImageEntries(options());
        const byPath = new Map(entries.map(entry => [entry.path, entry]));
        expect([...byPath.keys()].sort()).toEqual([
            ".DirIcon",
            "AppRun",
            "LICENSE.electron.txt",
            "resources/app.asar",
            "skeleton-12",
            "skeleton-12.desktop",
            "skeleton-12.png",
            "usr/lib/libXss.so.1",
            "usr/lib/libXss.so.1.0.0",
            "usr/share/icons/hicolor/16x16/apps/skeleton-12.png",
            "usr/share/icons/hicolor/256x256/apps/skeleton-12.png",
            "usr/share/icons/hicolor/64x64/apps/skeleton-12.png",
        ]);
        expect(byPath.get("AppRun")).toMatchObject({ kind: "file", mode: 0o755 });
        expect(byPath.get("skeleton-12.desktop")).toMatchObject({ kind: "file", mode: 0o644 });
        // Both links name the largest icon, whatever order the icons came in.
        expect(byPath.get("skeleton-12.png")).toEqual({ kind: "symlink", path: "skeleton-12.png", target: "usr/share/icons/hicolor/256x256/apps/skeleton-12.png" });
        expect(byPath.get(".DirIcon")).toEqual({ kind: "symlink", path: ".DirIcon", target: "usr/share/icons/hicolor/256x256/apps/skeleton-12.png" });
        expect(byPath.get("usr/lib/libXss.so.1")).toEqual({ kind: "symlink", path: "usr/lib/libXss.so.1", target: "libXss.so.1.0.0" });
    });

    it("lets the app replace a staged file, as a copy over the staging folder does", () => {
        const entries = appImageEntries(options({
            app: [{ kind: "file", path: "usr/lib/libXss.so.1.0.0", mode: 0o755, content: Buffer.from("the app's own") }],
        }));
        const replaced = entries.filter(entry => entry.path === "usr/lib/libXss.so.1.0.0");
        expect(replaced).toHaveLength(1);
        expect(replaced[0]).toMatchObject({ mode: 0o755 });
    });

    it("stages a licence when one is given, and points the launcher at it", () => {
        const entries = appImageEntries(options({ license: { fileName: "license.txt", content: Buffer.from("terms") } }));
        expect(entries.find(entry => entry.path === "license.txt")).toMatchObject({ kind: "file", mode: 0o644 });
        const appRun = entries.find(entry => entry.path === "AppRun");
        expect(Buffer.from((appRun as { content: Uint8Array }).content).toString()).toContain('--filename="$APPDIR/license.txt"');
    });

    it("refuses what electron-builder refuses", () => {
        expect(() => appImageEntries(options({ icons: [] }))).toThrow(/icon/);
        expect(() => appImageEntries(options({ executableName: "a/b" }))).toThrow(/executableName/);
        expect(() => appImageEntries(options({ productFilename: "a$b" }))).toThrow(/productFilename/);
    });

    it("is compressed with zstd, as electron-builder compresses a static-runtime AppImage at maximum", () => {
        expect(appImageCompression()).toBe(squashfsZstdAvailable() ? "zstd" : "gzip");
    });
});

describe("an AppImage file", () => {
    it("is the runtime with the image straight after it", async () => {
        const dir = await fs.mkdtemp(path.join(os.tmpdir(), "nl-appimage-"));
        try {
            const output = path.join(dir, "game.AppImage");
            const toolset = fakeToolset();
            const result = await writeAppImage(output, options({ toolset }));
            const file = await fs.readFile(output);
            expect(result).toEqual({ size: file.length, offset: toolset.runtime.length });
            expect(file.subarray(0, toolset.runtime.length)).toEqual(toolset.runtime);
            const read = readSquashfs(file.subarray(result.offset));
            const byPath = new Map(read.entries.map(entry => [entry.path, entry]));
            expect(byPath.get("")).toMatchObject({ mode: 0o755, uid: 0, gid: 0 });
            expect(byPath.get("AppRun")).toMatchObject({ kind: "file", mode: 0o755 });
            expect(byPath.get("skeleton-12")).toMatchObject({ kind: "file", mode: 0o755 });
            expect(byPath.get("usr/lib/libXss.so.1")).toMatchObject({ kind: "symlink", target: "libXss.so.1.0.0" });
            expect(byPath.get("skeleton-12.desktop")!.data!.toString()).toBe(appImageDesktopEntry(options()));
        } finally {
            await fs.rm(dir, { recursive: true, force: true });
        }
    });

    it("leaves nothing behind when the image cannot be written", async () => {
        const dir = await fs.mkdtemp(path.join(os.tmpdir(), "nl-appimage-"));
        try {
            const output = path.join(dir, "game.AppImage");
            await expect(writeAppImage(output, options({
                app: [{ kind: "file", path: "bad\\path", mode: 0o644, content: Buffer.alloc(0) }],
            }))).rejects.toThrow(/backslash/);
            await expect(fs.access(output)).rejects.toThrow();
        } finally {
            await fs.rm(dir, { recursive: true, force: true });
        }
    });
});
