/**
 * The cherry petal, as a bitmap.
 *
 * ## Why a bitmap and not a shape
 *
 * The other two seeds are lights: a snowflake and a raindrop are round or long, and an ellipse with a
 * soft falloff is not an approximation of them, it is what they look like. A petal is not. It has an
 * outline (ovate, notched at the tip) and it has *tone* across that outline - the tip catches more
 * light than the base, the edge thins, the midrib runs down it. The tone is the half a formula does
 * not give you, and at the sizes sakura renders at (52px across in the near layer at 1080p, 10px in
 * the far one) it is the half that reads.
 *
 * ## Why it is bytes in a source file
 *
 * The same renderer runs in the main process (the bake), in the workspace (the live preview) and in
 * the runtime bundle. A PNG would need a decoder in all three, and the one that does not have one is
 * the bake - no DOM, no `createImageBitmap`. A single channel of raw luminance needs no decoding
 * anywhere, and 64x64 of it is four kilobytes.
 *
 * ## What one byte means
 *
 * How much light this part of the petal adds, before the particle's own depth gain and the seed's
 * tint. Zero is outside the petal. There is no alpha channel here for the same reason the clip has
 * none: everything is light added onto black.
 */

/** Both dimensions. Square, so a rotation needs no second bound. */
export const PETAL_SPRITE_SIZE = 64;

/** 64x64 single-channel luminance, row-major from the petal's base to its tip. */
const PETAL_SPRITE_BASE64 = [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQcHBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAcPFBcXFxcUDwcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAChUdIiYnJycnJiIdFQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ",
    "FyIqMDU4ODc3ODg1MCoiFwkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVIy43PkRISkpI",
    "SEpKSEQ+Ny4jFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4gLzpETFJYW1xbWlpbXFtYUkxE",
    "Oi8gDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgqOUVQWWFna25ubWxsbW5ua2dhWVBFOSoYAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCAzQ1BcZm51e3+BgYB+foCBgX97dW5mXFBDMyAEAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCc7TFpncnuDipCTlJSTkZGTlJSTkIqDe3JnWkw7JwwAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAADyo+T15qdoCJkJabnp+enJubnJ6fnpuWkImAdmpeTz4qDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAADyk8TVtodH6GjpWanqChoJ6dnZ6goaCempWOhn50aFtNPCkPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSc6",
    "SlllcXuEjJOZnqGio6Kgn5+goqOioZ6Zk4yEe3FlWUo6Jw0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCM3R1VibniBiZGX",
    "nKCjpKSjoqGhoqOkpKOgnJeRiYF4bmJVRzcjCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4yQ1FeanV+h46Vm6CjpaampaSj",
    "o6Slpqalo6CblY6HfnVqXlFDMh4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgtPk1aZnF6g4uSmZ6ipqioqKelpaWlp6ioqKai",
    "npmSi4N6cWZaTT4tGAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mOEdVYWx2gIiPlpyhpaiqqqqop6amp6iqqqqopaGclo+IgHZs",
    "YVVHOCYPAAAAAAAAAAAAAAAAAAAAAAAAAAAeMUFPXGhye4SMk5mfpKeqrKyrqqmoqKmqq6ysqqekn5mTjIR7cmhcT0ExHgAA",
    "AAAAAAAAAAAAAAAAAAAAAAATKTpJVmJtd4CIkJacoqaqrK2urayrqqqrrK2urayqpqKclpCIgHdtYlZJOikTAAAAAAAAAAAA",
    "AAAAAAAAAAADHjFBT1xncnuEjJOZn6SprK6vr6+trKysrK2vr6+urKmkn5mTjIR7cmdcT0ExHgMAAAAAAAAAAAAAAAAAAAAA",
    "ESc4R1VhbHZ/h4+WnKKnq66wsbGwr66tra6vsLGxsK6rp6Kclo+Hf3ZsYVVHOCcRAAAAAAAAAAAAAAAAAAAAABouPkxZZXB5",
    "goqSmZ+kqa2wsrOzsrGvr6+vsbKzs7Kwramkn5mSioJ5cGVZTD4uGgAAAAAAAAAAAAAAAAAAAAkhM0NRXWlzfIWNlJuhpquv",
    "srO0tLOysbCwsbKztLSzsq+rpqGblI2FfHNpXVFDMyEJAAAAAAAAAAAAAAAAAAARJzhHVGFsdn+IkJedo6mtsbO1tra1tLOy",
    "srO0tba2tbOxramjnZeQiH92bGFURzgnEQAAAAAAAAAAAAAAAAAAFys8SlhjbniCipKZn6Wqr7K1t7e3trW0s7O0tba3t7e1",
    "sq+qpZ+ZkoqCeG5jWEo8KxcAAAAAAAAAAAAAAAAAABsuP01aZnF7hIyUm6GnrLG0t7i5ubi3trW1tre4ubm4t7SxrKehm5SM",
    "hHtxZlpNPy4bAAAAAAAAAAAAAAAAAAEdMUFPXGhzfIaOlp2jqa6ytri6u7q5uLe3t7e4ubq7uri2sq6po52WjoZ8c2hcT0Ex",
    "HQEAAAAAAAAAAAAAAAAEHzJCUV1pdH6Hj5eepaqvtLe6vLy8u7q5uLi5uru8vLy6t7SvqqWel4+HfnRpXVFCMh8EAAAAAAAA",
    "AAAAAAAABSAzQ1FeanV/iJGYoKassbW5u72+vby7urq6uru8vb69u7m1saymoJiRiH91al5RQzMgBQAAAAAAAAAAAAAAAAQg",
    "M0NSX2t2gImSmqGnrbK3ur2/v7++vby7u7y9vr+/v726t7Ktp6GakomAdmtfUkMzIAQAAAAAAAAAAAAAAAAAHjJDUl9rdoCK",
    "kpqiqK60uLy+wMHAv769vLy9vr/AwcC+vLi0rqiimpKKgHZrX1JDMh4AAAAAAAAAAAAAAAAAABwxQlFea3aBipOboqmvtbm9",
    "wMHCwsHAv76+v8DBwsLBwL25ta+popuTioF2a15RQjEcAAAAAAAAAAAAAAAAAAAYLkBPXWp2gIqTnKOqsLa6vsHDxMPCwcC/",
    "v8DBwsPEw8G+urawqqOck4qAdmpdT0AuGAAAAAAAAAAAAAAAAAAAEys9TVxpdYCKk5yjq7G3u7/CxMXFxMPBwcHBw8TFxcTC",
    "v7u3saujnJOKgHVpXE09KxMAAAAAAAAAAAAAAAAAAAwmOktaZ3R/iZOcpKuxt7zAxMXGxsXEw8LCw8TFxsbFxMC8t7GrpJyT",
    "iX90Z1pLOiYMAAAAAAAAAAAAAAAAAAAAIDVHV2VyfoiSm6Srsri9wcXHyMjHxcTDw8TFx8jIx8XBvbiyq6Sbkoh+cmVXRzUg",
    "AAAAAAAAAAAAAAAAAAAAABgvQlNib3yHkZujq7K4vsLGyMnJyMfGxcXGx8jJycjGwr64squjm5GHfG9iU0IvGAAAAAAAAAAA",
    "AAAAAAAAAAANKD1OXmx5hZCao6uyub7Dx8nKy8rIx8bGx8jKy8rJx8O+ubKro5qQhXlsXk49KA0AAAAAAAAAAAAAAAAAAAAA",
    "AB82SVppdoOOmKKqsrm/xMjKzMzLysjIyMjKy8zMysjEv7myqqKYjoN2aVpJNh8AAAAAAAAAAAAAAAAAAAAAAAASLUJUZHJ/",
    "i5agqbG5v8TJy83NzcvKycnKy83NzcvJxL+5samglot/cmRUQi0SAAAAAAAAAAAAAAAAAAAAAAAAACI5TV5ufIiUnqixuL/F",
    "yczOz87Ny8rKy83Oz87MycW/uLGonpSIfG5eTTkiAAAAAAAAAAAAAAAAAAAAAAAAAAASL0VXaHeFkZymr7i/xcrNz9DPzs3M",
    "zM3Oz9DPzcrFv7ivppyRhXdoV0UvEgAAAAAAAAAAAAAAAAAAAAAAAAAAACE6T2FygI2ZpK63vsXKztHR0c/Ozc3Oz9HR0c7K",
    "xb63rqSZjYByYU86IQAAAAAAAAAAAAAAAAAAAAAAAAAAAAANLUVZa3uJlqGstb7Fys/S09LRz87Oz9HS09LPysW+tayhlol7",
    "a1lFLQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABw4T2N0g5GeqbO8xMrP09TU0tHPz9HS1NTTz8rEvLOpnpGDdGNPOBwAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAJ0JYbH2Mmqaxu8PK0NPV1dTS0dHS1NXV09DKw7uxppqMfWxYQicAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAABAyTGJ1hZWirrnCytDU1tbV09LS09XW1tTQysK5rqKVhXViTDIQAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAHDxVan2Onaq2wMnQ1dfYzsfCwsfO2NfV0MnAtqqdjn1qVTwcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAm",
    "RV5zhpelsr3Hz8e8sKaempqeprC8x8/HvbKll4ZzXkUmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9NZnyPn666",
    "ua6hlIh9dXFxdX2IlKGuubqun498Zk0vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOOFZvhJeooZaJe21gVExI",
    "SExUYG17iZahqJeEb1Y4DgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhAXneNioF1ZlZGNysiHh4iKzdGVmZ1",
    "gYqNd15AGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH0dmb2xjVUQxHw8BAAAAAAEPHzFEVWNsb2ZHHwAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmR1JRRzckDgAAAAAAAAAAAAAOJDdHUVJHJgAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACM2Ny4dBgAAAAAAAAAAAAAAAAYdLjc2IwAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAGiEYBgAAAAAAAAAAAAAAAAAABhghGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAOCAAAAAAAAAAAAAAAAAAAAAAIDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",].join("");

let decoded: Uint8Array | null = null;

/**
 * The sprite, decoded once.
 *
 * Lazily rather than at module load: every host that imports the field builder pays for this table,
 * and a project with no sakura in it should not. Once decoded it is shared - nothing writes to it.
 */
export function petalSprite(): Uint8Array {
    if (decoded) {
        return decoded;
    }
    const binary = typeof atob === "function"
        ? atob(PETAL_SPRITE_BASE64)
        : Buffer.from(PETAL_SPRITE_BASE64, "base64").toString("binary");
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
    }
    decoded = bytes;
    return bytes;
}
